name: NPM Deprecate PR versions On Merge

on:
  pull_request:
    types:
      - closed

jobs:
  deprecate-on-merge:
    name: NPM Deprecate PR versions On Merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js v20
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-frozen-lockfile
      - name: Deprecate versions
        run: pnpm npm-deprecate --name "*pr-${PR_NUMBER}*" -d -v
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
